### ISSUE TITLE
License BSD-2-Clause OR BSD-3-Clause or BSD-2-Clause AND BSD-3-Clause

### ISSUE THREAD

**Issue by IlyaIndigo** [MusicPlayerDaemon/libmpdclient#121]
License
BSD-2-Clause OR BSD-3-Clause
or
BSD-2-Clause AND BSD-3-Clause
?

**Comment by MaxKellermann** [comment]
Some source files are BSD-2 and some are BSD-3. I'd agree to make all my code BSD-2, but there was older code by other people that was put on BSD-3.

**Comment by IlyaIndigo** [comment]
BSD-2-Clause AND BSD-3-Clause
