### ISSUE TITLE
problem with connection

### ISSUE THREAD

**Issue by Old-Geek** [MusicPlayerDaemon/libmpdclient#15]
Hello,

I am developing a MPD client for mac OS (Xcode 10, Mojave), everything works fine except the connection management.

After a certain delay MPD closes the connection and can not reconnect.

I tried a failed mpd_connexion_free, mpd_connection_set_keepalive no effect, mpd_connection_set_timeout no effect.

------------------------------------------------------------------
       mpd_connection_free(mpd1Connection);         
        mpd1Connection = mpd_connection_new(host, port, 0);
------------------------------------------------------------------

error: Failed ti resolve hostname

Would you have a way to give me?

**Comment by MaxKellermann** [comment]
If MPD closes the connection, there's nothing libmpdclient can do about it.
This has nothing to do with keepalive - that's TCP level keepalive, and will not keep MPD from disconnecting an idle client.
Not a libmpdclient issue.
