### ISSUE TITLE
Add a mpd_album_get_uri function

### ISSUE THREAD

**Issue by Nyx0uf** [MusicPlayerDaemon/libmpdclient#17]
I'm developing an open source iOS app to remote control MPD.
My music library is organised like this `music_dir/albums_artists/albums`; Each album folder contain the songs and a *cover.jpg* file.

Currently to obtain the album path in order to download covers I have to do something like :

1. `mpd_search_db_songs(connection, true)`
2. `mpd_search_add_tag_constraint(connection, MPD_OPERATOR_DEFAULT, MPD_TAG_ALBUM, album_name)`
3. `mpd_recv_song(connection)` / `mpd_song_get_uri(song)`

Would it be possible to have a single function that returns the URI given the `album_name` ? Or am I doing things the wrong way ?

Thanks.

**Comment by MaxKellermann** [comment]
That would be possible, and you can do that in your client, but it would not be useful to add such a thing to libmpdclient. That would mean we'd have to add hundreds of combinations for every special case one could imagine. But libmpdclient shall be a generic library with small low-level functions.

**Comment by Nyx0uf** [comment]
Ok, thanks for your answer, I'm closing the issue.
