### ISSUE TITLE
Support of albumart command

### ISSUE THREAD

**Issue by jcorporation** [MusicPlayerDaemon/libmpdclient#21]
Libmpdclient doesn't support the new albumart command.

I tried to implement it myself, but I don't know how I get the binary data. Is there a appropriated way in libmpdclient?

**Comment by jcorporation** [comment]
I managed to get the size and binary pair with ``mpd_recv_pair_named`` and the binary data with ``mpd_sync_recv_line`` but how I finish the response properly?

I tried:

-  ``mpd_response_finish`` -> throws an error
- ``setting connection->receiving = false`` throws an error at the next command ``Failed to parse MPD response``

I tested it with mpd and libmpdclient from master. You can find my attempts in the src/albumart.c file in my libmpdclient fork: https://github.com/jcorporation/libmpdclient

**Comment by jcorporation** [comment]
It seems that ``mpd_sync_recv_line`` don't handle the binary data correctly. A second ``mpd_sync_recv_line`` should receive the final "OK" and that fails.

**Comment by MaxKellermann** [comment]
Of course, `mpd_sync_recv_line` is for text mode, you can't use it for binary mode.

**Comment by jcorporation** [comment]
ok, is there a function for binary mode in libmpdclient or must I implement it myselfe?

**Comment by duganchen** [comment]
As libmpdclient does not currently support the albumart command, may I request a comment on why this was closed?

**Comment by Nyx0uf** [comment]
+1

It would be nice if the albumart command could be implemented in libmpdclient.

**Comment by jcorporation** [comment]
My fork implements support for albumart and readpicture commands. Give me some time to create a pull request.

**Comment by jcorporation** [comment]
Mercedes with #73
