### ISSUE TITLE
Error in meson.build

### ISSUE THREAD

**Issue by MagikBSD** [MusicPlayerDaemon/libmpdclient#3]
After I called: `meson . output` I saw an error mesage:

> The Meson build system
> Version: 0.40.1
> Source dir: /home/magik/Downloads/libmpdclient-2.12
> Build dir: /home/magik/Downloads/libmpdclient-2.12/output
> Build type: native build
> Project name: libmpdclient
> Native c compiler: cc (gcc 5.4.0)
> Build machine cpu family: x86_64
> Build machine cpu: x86_64
> Checking for function "getaddrinfo": YES
> Configuring config.h using configuration
> Configuring version.h using configuration
> Compiler for c supports argument -Wall: YES
> Compiler for c supports argument -Wextra: YES
> Compiler for c supports argument -Wno-deprecated-declarations: YES
> Compiler for c supports argument -Wmissing-prototypes: YES
> Compiler for c supports argument -Wshadow: YES
> Compiler for c supports argument -Wpointer-arith: YES
> Compiler for c supports argument -Wstrict-prototypes: YES
> Compiler for c supports argument -Wcast-qual: YES
> Compiler for c supports argument -Wwrite-strings: YES
> Compiler for c supports argument -Wl,--version-script=/home/magik/Downloads/libmpdclient-2.12/libmpdclient.ld: YES
> 

> 
> Meson encountered an error in file meson.build, line 88, column 0:
> Tried to form an absolute path to a source dir. You should not do that but use
> relative paths instead.
> 
> To get include path to any directory relative to the current dir do
> 
> incdir = include_directories(dirname)
> 
> After this incdir will contain both the current source dir as well as the
> corresponding build dir. It can then be used in any subdirectory and
> Meson will take care of all the busywork to make paths work.
> 
> Dirname can even be '.' to mark the current directory. Though you should
> remember that the current source and build directories are always
> put in the include directories by default so you only need to do
> include_directories('.') if you intend to use the result in a
> different subdirectory.

I tried this command on two different systems (Mint Linux 18.2 & FreeBSD 11.0) with similar result.
This error message is from Mint Linux.

**Comment by ilovezfs** [comment]
@MagikBSD See https://github.com/MusicPlayerDaemon/libmpdclient/pull/4.

**Comment by MaxKellermann** [comment]
ad0db0a2e18dc85aa6b9cc81b269510386d71981
