### ISSUE TITLE
Homebrew library breaks mpd clients

### ISSUE THREAD

**Issue by GhostValk** [MusicPlayerDaemon/libmpdclient#5]
After upgrading to 2.12, i'm unable to connect to mpd with any mpd client.

Mpc outputs;

`dyld: Library not loaded: /usr/local/opt/libmpdclient/lib/libmpdclient.2.dylib
  Referenced from: /usr/local/bin/mpc
  Reason: Incompatible library version: mpc requires version 3.0.0 or later, but libmpdclient.2.dylib provides version 0.0.0
`

Any idea what could it be?

I'm using OSX 10.12.

**Comment by MaxKellermann** [comment]
No, I have no idea. A version 3.0.0 does not exist, thus I must assume that your previous libmpdclient build was from a fork, not the official version. And that fork did not care to retain ABI compatibility with this official version.

**Comment by GhostValk** [comment]
Nope, my previous one was 2.11, built with homebrew also from the master. All the mpd clients i have, that depend on libmpdclient got broken after the update (ncmpcpp, vimpc, mpc). I tried rebuilding them all after upgrading, with the same result.

**Comment by MaxKellermann** [comment]
Your error message clearly said you've been using version 3.0.0, and that is not a software developed by this project.

**Comment by GhostValk** [comment]
No, that error doesn't say "i've been using version 3.0.0,", it says that mpc now is asking for that version and the installed lib is reporting a different one.

As i said, i've never compiled or cloned any other libmpdclient repo or branch different from the master, always the Homebrew one which is the master branch.

The problem started when upgrading from 2.11 to 2.12.

**Comment by ilovezfs** [comment]
@MaxKellermann the library version number change on macOS from 3.0.0 to 0.0.0 is a product of the build system change from Autotools to meson. This corresponds to the upgrade in Homebrew from 2.11 to 2.12.

**Comment by ilovezfs** [comment]
@MaxKellermann 
```
==> Installing libmpdclient
==> Downloading https://www.musicpd.org/download/libmpdclient/2/libmpdclient-2.11.tar.gz
######################################################################## 100.0%
==> ./configure --prefix=/usr/local/Cellar/libmpdclient/2.11
==> make install
🍺  /usr/local/Cellar/libmpdclient/2.11: 168 files, 2.1MB, built in 11 seconds
iMac-TMP:homebrew-core joe$ otool -L /usr/local/Cellar/libmpdclient/2.11/lib/libmpdclient.dylib 
/usr/local/Cellar/libmpdclient/2.11/lib/libmpdclient.dylib:
	/usr/local/opt/libmpdclient/lib/libmpdclient.2.dylib (compatibility version 3.0.0, current version 3.11.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
iMac-TMP:homebrew-core joe$ 
```
