### ISSUE TITLE
combination of mpd_search_add_any_tag_constraint & mpd_search_add_uri_constraint

### ISSUE THREAD

**Issue by eMPee584** [MusicPlayerDaemon/libmpdclient#57]
In ncmpcpp, I had a look at making a search on "any" also search file names.. But it seems to be a constraint in the libmpdclient implementation that `any` does not search URIs.. Is there any point in this and what could be done to overcome this inconvenience.. Thanks in advance ; )

**Comment by cataldor** [comment]
Hello @eMPee584 
I'm not sure i understand what you want to do

the `any` keyword is a special case for searching all tags [1]
if you want to search filenames you would use the `file` constraint (`mpd_search_add_uri_constraint`)
note that you have to match the full song URI (check mpd protocol [1])
could you provide an example of what you would like to do?

[1] https://www.musicpd.org/doc/html/protocol.html

**Comment by MaxKellermann** [comment]
This has nothing to do with libmpdclient.
@cataldor explained it well.
