### ISSUE TITLE
rpmbuild on fedora 25 failed 

### ISSUE THREAD

**Issue by dominik96** [MusicPlayerDaemon/libmpdclient#7]
I am now trying to build 45 minutes from the tarball a rpm package, but does not work.

%build
export CFLAGS="%{optflags} -Os -fPIC -fuse-ld=gold -fuse-linker-plugin"
export CXXFLAGS="$CFLAGS"
export CC="gcc $CFLAGS"
export LDFLAGS="-Wl,--as-needed -Wl,-z,now -Wl,-z,relro -Wl,-z,noexecstack %{optflags} -Os -fuse-ld=gold -fuse-linker-plugin"
meson . dksoft-build
ninja -C dksoft-build

%install
ninja -C dksoft-build install DESTDIR=%{buildroot}

Error:
"I think" meson does not support my DESTDIR, has someone an idea why it fails?

**Comment by dominik96** [comment]
[dsoft@buildsrv:~/rpmbuild/SPECS]$ rpmbuild -bb libmpdclient.spec 
Ausführung(%prep): /bin/sh -e /var/tmp/rpm-tmp.sxmGBa
+ umask 022
+ cd /home/dsoft/rpmbuild/BUILD
+ cd /home/dsoft/rpmbuild/BUILD
+ rm -rf libmpdclient-2.13
+ /usr/bin/xz -dc /home/dsoft/rpmbuild/SOURCES/libmpdclient-2.13.tar.xz
+ /usr/bin/tar -xof -
+ STATUS=0
+ '[' 0 -ne 0 ']'
+ cd libmpdclient-2.13
+ /usr/bin/chmod -Rf a+rX,u+w,g-w,o-w .
+ exit 0
Ausführung(%build): /bin/sh -e /var/tmp/rpm-tmp.wqgAN8
+ umask 022
+ cd /home/dsoft/rpmbuild/BUILD
+ cd libmpdclient-2.13
+ export 'CFLAGS=-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -march=core2 -mtune=core2  -Os -fPIC -fuse-ld=gold -fuse-linker-plugin'
+ CFLAGS='-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -march=core2 -mtune=core2  -Os -fPIC -fuse-ld=gold -fuse-linker-plugin'
+ export 'CXXFLAGS=-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -march=core2 -mtune=core2  -Os -fPIC -fuse-ld=gold -fuse-linker-plugin'
+ CXXFLAGS='-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -march=core2 -mtune=core2  -Os -fPIC -fuse-ld=gold -fuse-linker-plugin'
+ export 'CC=gcc -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -march=core2 -mtune=core2  -Os -fPIC -fuse-ld=gold -fuse-linker-plugin'
+ CC='gcc -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -march=core2 -mtune=core2  -Os -fPIC -fuse-ld=gold -fuse-linker-plugin'
+ export 'LDFLAGS=-Wl,--as-needed -Wl,-z,now -Wl,-z,relro -Wl,-z,noexecstack -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -march=core2 -mtune=core2  -Os -fuse-ld=gold -fuse-linker-plugin'
+ LDFLAGS='-Wl,--as-needed -Wl,-z,now -Wl,-z,relro -Wl,-z,noexecstack -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -march=core2 -mtune=core2  -Os -fuse-ld=gold -fuse-linker-plugin'
+ meson . output
WARNING: You are using 'ANSI_X3.4-1968' which is not a a Unicode-compatible locale.
WARNING: You might see errors if you use UTF-8 strings as filenames, as strings, or as file contents.
WARNING: Please switch to a UTF-8 locale for your platform.
The Meson build system
Version: 0.41.1
Source dir: /data/dokuments/rpmbuild/BUILD/libmpdclient-2.13
Build dir: /data/dokuments/rpmbuild/BUILD/libmpdclient-2.13/output
Build type: native build
Project name: libmpdclient
Native c compiler: gcc -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -march=core2 -mtune=core2 -Os -fPIC -fuse-ld=gold -fuse-linker-plugin (gcc 6.3.1)
Appending CFLAGS from environment: '-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -march=core2 -mtune=core2  -Os -fPIC -fuse-ld=gold -fuse-linker-plugin'
Appending LDFLAGS from environment: '-Wl,--as-needed -Wl,-z,now -Wl,-z,relro -Wl,-z,noexecstack -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -march=core2 -mtune=core2  -Os -fuse-ld=gold -fuse-linker-plugin'
Build machine cpu family: x86_64
Build machine cpu: x86_64
Checking for function "getaddrinfo": YES
Configuring config.h using configuration
Configuring version.h using configuration
Compiler for c supports argument -Wall: YES
Compiler for c supports argument -Wextra: YES
Compiler for c supports argument -Wno-deprecated-declarations: YES
Compiler for c supports argument -Wmissing-prototypes: YES
Compiler for c supports argument -Wshadow: YES
Compiler for c supports argument -Wpointer-arith: YES
Compiler for c supports argument -Wstrict-prototypes: YES
Compiler for c supports argument -Wcast-qual: YES
Compiler for c supports argument -Wwrite-strings: YES
Compiler for c supports argument -Wl,--version-script=/data/dokuments/rpmbuild/BUILD/libmpdclient-2.13/libmpdclient.ld: YES
Build targets in project: 2
+ ninja -C output
ninja: Entering directory `output'
[45/46] Generating symbol file 'mpdclient@sha/libmpdclient.so.2.13.symbols'.
WARNING: You are using 'ANSI_X3.4-1968' which is not a a Unicode-compatible locale.
WARNING: You might see errors if you use UTF-8 strings as filenames, as strings, or as file contents.
WARNING: Please switch to a UTF-8 locale for your platform.
[46/46] Linking target example.
+ exit 0
Ausführung(%install): /bin/sh -e /var/tmp/rpm-tmp.iJprqg
+ umask 022
+ cd /home/dsoft/rpmbuild/BUILD
+ '[' /home/dsoft/rpmbuild/BUILDROOT/libmpdclient-2.13-1.fc25.20170725.dk.x86_64 '!=' / ']'
+ rm -rf /home/dsoft/rpmbuild/BUILDROOT/libmpdclient-2.13-1.fc25.20170725.dk.x86_64
++ dirname /home/dsoft/rpmbuild/BUILDROOT/libmpdclient-2.13-1.fc25.20170725.dk.x86_64
+ mkdir -p /home/dsoft/rpmbuild/BUILDROOT
+ mkdir /home/dsoft/rpmbuild/BUILDROOT/libmpdclient-2.13-1.fc25.20170725.dk.x86_64
+ cd libmpdclient-2.13
+ ninja -v -C output install DESTDIR=/home/dsoft/rpmbuild/BUILDROOT/libmpdclient-2.13-1.fc25.20170725.dk.x86_64
ninja: Entering directory `output'
ninja: error: unknown target 'DESTDIR=/home/dsoft/rpmbuild/BUILDROOT/libmpdclient-2.13-1.fc25.20170725.dk.x86_64'
Fehler: Fehler-Status beim Beenden von /var/tmp/rpm-tmp.iJprqg (%install)


Fehler beim Bauen des RPM:
    Fehler-Status beim Beenden von /var/tmp/rpm-tmp.iJprqg (%install)

**Comment by MaxKellermann** [comment]
Bug is in your build script. And Google is your friend!
http://mesonbuild.com/Installing.html#destdir-support
