### ISSUE TITLE
Status sets duration from deprecated time field

### ISSUE THREAD

**Issue by pcewing** [MusicPlayerDaemon/libmpdclient#70]
I've been implementing an MPD client in Go and using this library as a reference and I noticed something while comparing the implementation of `mpd_status_feed` to the protocol docs.

From the docs:
```
time: total time elapsed (of current playing/paused song) in seconds (deprecated, use elapsed instead)
elapsed: Total time elapsed within the current song in seconds, but with higher resolution.
duration: Duration of the current song in seconds.
```

It looks like the `time` field has been deprecated in the protocol in favor of `elapsed` and `duration`. `libmpdclient` supports the new `elapsed` field; however, it still reads the total time of the current song from the `time` field instead of `duration`:
https://github.com/MusicPlayerDaemon/libmpdclient/blob/1315357229cd5dd858c098d28e85c8cf6d5ed008/src/status.c#L246-L251

This is low priority as I imagine the `time` field won't be removed any time soon for back-compat reasons but just thought I'd point it out.

I wouldn't mind implementing the fix myself but it does raise the question of how to handle the case where both `time` and `duration` are present in the response. Ideally, the value of `duration` would be favored; however, that could be more difficult than it sounds given how the library reads line-by-line. I know the server reports the version in the initial connection process and I imagine `libmpdclient` probably stores this somewhere. Maybe if the version is `>=0.20` we ignore the `time` field and just use `elapsed` & `duration`?

Edit: Another thought is the new `duration` field provides millisecond precision so this has an added functional benefit other than just code clean up

**Comment by jcorporation** [comment]
It is simple: do not use the time field as user of the library -> do not use `mpd_status_get_elapsed_time`. Deprecation is documented in the header file.
