### ISSUE TITLE
Question: how to implement the new position parameter for load?

### ISSUE THREAD

**Issue by jcorporation** [MusicPlayerDaemon/libmpdclient#76]
Hi Max,

I would implement the position parameter for the load command and have a question:

Current we have these functions to load a playlist into the queue.

- mpd_send_load
- mpd_run_load
- mpd_send_load_range
- mpd_run_load_range

Should be following functions added? This would hide the special 0: range specification.

- mpd_send_load_position
- mpd_run_load_position
- mpd_send_load_range_position
- mpd_run_load_range_position

Will this position parameter also support whence as addid or searchadd?

**Comment by MaxKellermann** [comment]
I'd like to haver fewer functions with more complex parameters. So we need to find an API which supports both range and position parameters, with all the features supported by MPD.
Yes, all queue positions should support relative positions. They will in MPD, and a libmpdclient API should already support the feature, even if MPD doesn't have it yet.
