### ISSUE TITLE
incomplete type ‘struct mpd_status’

### ISSUE THREAD

**Issue by matthiakl** [MusicPlayerDaemon/libmpdclient#86]
I'm using `libmpdclient` in a C++ project. When I try to use `struct mpd_status` like in the snippet below, the compiler complains about `invalid use of incomplete type ‘struct mpd_status’`. 
It looks like the reason for it is that this struct is defined in a .c file. Is there a way to make it accessible to C++? For now I moved the definition into `status.h`.
```
struct mpd_status * status = mpd_run_status(connection);
skip = (status->state != MPD_STATE_PLAY);
mpd_status_free(status);
```

**Comment by MaxKellermann** [comment]
You are not supposed to dereference this struct, and it is intentionally incomplete, because its internal layout can change at any time.
Instead, use the getter functions like `mpd_status_get_state()`.
