### ISSUE TITLE
[Question] About the Vapi

### ISSUE THREAD

**Issue by Miqueas** [MusicPlayerDaemon/libmpdclient#97]
Hi, I just wanna know how much is the Vapi updated. Last commit was in 2015, ¿there are so much changes since that?

**Comment by MaxKellermann** [comment]
It was contributed by somebody who never cared about keeping it up to date. It is therefore unmaintained - I don't even know what use this Vapi is.

**Comment by Miqueas** [comment]
> It was contributed by somebody who never cared about keeping it up to date. It is therefore unmaintained - I don't even know what use this Vapi is.

I see,thanks anyway!
